### ISSUE TITLE
How can I use eddymotion for my own dMRI data?

### ISSUE THREAD

**Issue by jrf1024** [nipreps/eddymotion#126]
### What would you like changed/added and why?

How can I use eddymotion to analyze my own dMRI data? Is there a pipeline, a tutorial or example? Please help me!

### Do you have any interest in helping improve the documentation?

Yes

**Comment by oesteban** [comment]
In addition to #169, there's nothing we can do today. Hopefully, with the new energy of the past few months, a version that is amenable to third-party users will be able to see the light. Stay tuned for that!

**Comment by jrf1024** [comment]
您的邮件已收到。
