### ISSUE TITLE
Allow initializing the DWI object with "bvals"/"bvecs" 

### ISSUE THREAD

**Issue by arokem** [nipreps/eddymotion#170]
Right now, we require a RAS + b file:

https://github.com/nipreps/eddymotion/blob/b1f70cc67417ac2fab43ccf5196b9b26397b2326/src/eddymotion/data/dmri.py#L59

Would be good to allow the FSL format for bval/bvec files as well.

**Comment by oesteban** [comment]
There is a commodity `load()` function to do that:

https://github.com/nipreps/eddymotion/blob/b22efd5e6f9ae6da166dc70409f17dde84359ed0/src/eddymotion/data/dmri.py#L187-L244

Would that resolve the question completely or you would like to see something else implemented?

**Comment by arokem** [comment]
Yes - I think that resolves my question completely. Closing.
