### ISSUE TITLE
Q: Why our releases jump from 0.1.4 to 0.1.15?

### ISSUE THREAD

**Issue by oesteban** [nipreps/eddymotion#197]
With the latest release, we seem to have skipped a number of patch releases: https://pypi.org/project/eddymotion/#history

What was the rationale behind this? I don't think this is a big deal at this moment of the development of the package (other than renaming a milestone https://github.com/nipreps/eddymotion/milestone/4), but perhaps there was some blocker/problem that might have gone undetected.

cc/ @effigies @esavary

**Comment by effigies** [comment]
I think it was probably a typo in the issue title:

* #152

**Comment by oesteban** [comment]
Ha, you're right - that likely dragged the whole thing. Do we want to add some checks to the release pipeline and/or use setuptools_scm to suggest the new version name?

**Comment by effigies** [comment]
I feel like writing checks will be a lot of work for very little gain.

**Comment by oesteban** [comment]
Okay, nothing to do here. Let's just make sure we do not trust an issue title by me again.
