### ISSUE TITLE
Repository is HUGE

### ISSUE THREAD

**Issue by oesteban** [nipreps/eddymotion#55]
It takes way much longer than it should to clone. Will probably require some cleanup of the history and removing fat objects.

**Comment by arokem** [comment]
Do we know which are the large files that are causing this? Notebooks with images?

**Comment by oesteban** [comment]
Yes, there was an animated gif or PNG of more than 50MB. We will need to
clean old git objects

**Comment by mathdugre** [comment]
Listing of the git objects sorted by size.
```
ebf1fafd1556  107KiB docs/notebooks/Testing GP model.ipynb
a28faa1be6cc  119KiB demo.ipynb
06db45c264c8  136KiB demo.ipynb
977a1c8fc552  141KiB demo.ipynb
acf06152cfbd  185KiB demo.ipynb
0c6c6b4b446c  206KiB docs/notebooks/demo.ipynb
41aaa4590fa8  235KiB docs/notebooks/Plotting DWI.ipynb
deb23cb92511  923KiB eddymotion/tests/data/fbfx_b0.nii.gz
930ecaeda589  1.0MiB demo.ipynb
c8f7c5a07c04  6.1MiB eddymotion/tests/data/dwi.h5
289f597bc492   27MiB eddymotion/tests/data/fbfx_dti.nii.gz
94104abf6886   58MiB emc_reg.gif
9f71a344f5a8   64MiB data/sub-01_dwi.nii.gz
```

**Comment by arokem** [comment]
Thanks @mathdugre : I am going to try to deal with the files under `tests/data` and `data` first. 

My plan is to do an interactive rebase and force push to main, so I'll be back here to tell you all to pull from main when that's done. Wish me luck 🤞

**Comment by arokem** [comment]
@mathdugre : what command are you using to generate the list with the object sizes?

**Comment by mathdugre** [comment]
@arokem : I found this command on a [blog post](https://medium.com/tarkalabs-til/find-large-files-inside-your-git-repository-1e3eb45317c6).
```bash
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| awk '/^blob/ {print substr($0,6)}' \
| sort --numeric-sort --key=2 \
| cut --complement --characters=13-40 \
| numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

**Comment by arokem** [comment]
I think/hope this was resolved with [bfg](https://rtyley.github.io/bfg-repo-cleaner/). 

Everyone using this repository will need to make a **clean clone** of the repo, before continuing to work on anything.

**Comment by arokem** [comment]
Actually, stand by with this for now. Retrying now.

**Comment by arokem** [comment]
Looks like BFG is a deadend, so @mathdugre is trying https://github.com/newren/git-filter-repo instead

**Comment by mathdugre** [comment]
@arokem I pushed the version with large files filtered out, as well as the notebook files.
I couldn't make a PR directly since the history are entirely different. The changes can be found on the [`rebase_main`](https://github.com/mathdugre/eddymotion/tree/rebase_main) branch of my fork.

**Comment by oesteban** [comment]
I just did. Indeed, the repo is now down to 776.56 KiB. Good job.
