### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by arokem** [nipreps/eddymotion#93]
@nipreps/org-admins, please add me as a member.

Please check below the projects you anticipate you are more interested in:

- [ ] fMRIPrep
- [x] dMRIPrep
- [ ] PETPrep
- [ ] ASLPrep
- [ ] sMRIPrep
- [x] MRIQC
- [x] TemplateFlow
- [x] Other(s) : eddymotion

**Comment by oesteban** [comment]
Added to MRIQC and TemplateFlow, where you were missing :)
