### ISSUE TITLE
The issues templates options are slightly confusing

### ISSUE THREAD

**Issue by arokem** [nipreps/eddymotion#94]
When I saw this: 

![image](https://user-images.githubusercontent.com/118582/203674561-5ccb3f85-1fd2-4aac-a328-f2aae086431e.png)

I thought this was some kind of new-fangled thing, where I needed to become a member of the organization in order to post issues. It was only on my second visit that I noticed the text below the main menu. Maybe we should add some more options to that menu?

**Comment by oesteban** [comment]
That was my bad - I wanted to have an special issue type for the special repo `nipreps/.github` and it always overrides the existing issue templates. I have removed it.
